apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  labels:
    app: web-app
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80               # Port on the service (containerPort in deployment.yaml)
      targetPort: 80         # Port exposed by the container in the deployment
      nodePort: 30007        # Node port to access externally
